# /etc/fail2ban/filter.d/sshd-invalid-user.conf
[Definition]

# Ловим попытки с invalid/illegal user (только строки с IP-адресом)
failregex = ^.*sshd\[.*\]: Invalid user \S+ from <HOST>.*$
            ^.*sshd\[.*\]: User \S+ from <HOST> not allowed because not listed in AllowUsers.*$
            ^.*sshd\[.*\]: Connection closed by invalid user \S+ <HOST> port \d+.*$
            ^.*sshd\[.*\]: Failed password for invalid user \S+ from <HOST>.*$
            ^.*sshd\[.*\]: Disconnected from invalid user \S+ <HOST> port \d+.*$

ignoreregex =
